# .github/workflows/ci.yml
name: CI Workflow Example

on: # Trigger events
  push:
    branches:
      - develop
  pull_request:
    branches:
      - develop
  workflow_dispatch: # Allow manual triggers

jobs:
  build:
    runs-on: ubuntu-22.04 # Explicitly specify a stable Ubuntu version

    steps:
      # Checkout code
      - name: Checkout code
        uses: actions/checkout@v3

      # Setup Python environment
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11 # Use a supported Python version

      # Restore dependencies from cache
      - name: Restore dependencies cache
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      # Install dependencies
      - name: Install dependencies
        run: pip install -r requirements.txt

      # Run the script
      - name: Run script
        run: |
          python myapp.py > output.txt

      # Upload artifacts
      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: app-output
          path: output.txt

  test:
    runs-on: ubuntu-22.04 # Explicitly specify the Ubuntu version

    needs: build

    steps:
      # Download artifacts
      - name: Download artifacts
        uses: actions/download-artifact@v3
        with:
          name: app-output

      # Validate artifact
      - name: Validate artifact
        run: cat output.txt

        
